### ISSUE TITLE
Ideal cases in test directory

### ISSUE THREAD

**Issue by jhaley50667** [openwfm/WRF-SFIRE#42]
There are differences between the master branch and the wrf-fire-track/master branch for some of the test experiments within the test/em_fire directory. In the master branch, soft links to exe files are not always created and there are differences between the input_sounding, input_fc, and input_lu files that are found in the wrf-fire-track/master branch for the fireflux_small and two_fires experiments.

For testing purposes, the hill experiment has been run with identical settings in both the master and the wrf-fire-track/master branches. These runs may be found on the Kingspeak cluster on the following paths.

master:
/uufs/chpc.utah.edu/common/home/kochanski-group4/jhaley/wrf4/WRF-SFIRE/test/em_fire/hill_01
wrf-fire-track/master:
/uufs/chpc.utah.edu/common/home/kochanski-group4/jhaley/wrf3/WRF-SFIRE/wrfv2_fire/test/em_fire/hill_01

**Comment by janmandel** [comment]
@jhaley50667 
The test/em_fire directory contains both test problems from WRF and ours. WRF test problem subdirectories are created dynamically  by `./compile`,  populated by soft links to files in the parent directory, and destroyed by .`/clean -a`. Our test problems are static, committed to git, filtered from [the original wrf-fire repositores](https://github.com/openwfm/wrf-fire) 

Some of the test problem directories do not have soft links to wrf.exe and ideal.exe. in that case, scripts should execute the binaries in `../../../main`.

**Comment by janmandel** [comment]
test/em_fire/rain1 fixed to run both with ifire=1 and ifire=2.
This was caused by some changes required in the fuel moisture port in  WRF pull request #792, which caused namelist.fire to be incompatible with WRF-SFIRE ifire=1 
The contents of namelist.fire is however already in the code as defaults, so it was enough to delete the offending part of the &fuel_categories namelist.
Also, the `&moisture` namelist had to be renamed to `&fuel_moisture` in the pull request. Since the contents is again in the code as default, added empty namelist `&moisture`.

**Comment by janmandel** [comment]
@jhaley50667 fixed /glade/work/jmandel/WRF-SFIRE-rain-mpi/test/em_fire/rain1 0a634accb1ad3008e90ffda6fa8b894154c8dac7

**Comment by jhaley50667** [comment]
em_fire/rain1 has been tested on Frontera and found working with both ifire = 1 and ifire =2.

**Comment by janmandel** [comment]
Continued in #29
