### ISSUE TITLE
Emissions from WRF-SFire

### ISSUE THREAD

**Issue by Porkking** [openwfm/WRF-SFIRE#43]
Hi Dr. Mandel,
Is there a method to access the fire emissions when running the WRF-SFire with WRF-Chem? If not, what is the equation for online calculation for WRF-SFire? Is it fine to use the following equation to estimate?
For each fuel category
Emission_sub = fuel loading (fgi in namelist.fire) * consumed fraction (avg_fuel_frac: output from wrf-fire) * emission factor (factors in namelist.fire_emissions) * grid area
And the sum of emission for each fuel category is the total emission of the fire for a specific time step.
Thanks,
Zongrun

**Comment by Porkking** [comment]
I think the problem is solved. The emission can be printed by set:
```printsums=1```
Sorry for bothering.

**Comment by janmandel** [comment]
Just to confirm that I'll look into this. Thanks for your interest. Jan

**Comment by janmandel** [comment]
@Porkking 
The computation of emissions is done in [subroutine add_fire_emissions](https://github.com/openwfm/WRF-SFIRE/blob/681dc5a08b6ab5fe14938610eb5700a9d01abaf9/phys/module_fr_sfire_atm.F#L390)
The formula has also conversion of units and from 2D (emissions per m^2) to 3D (concentrations in the lowest WRF cell). The height of the cell is a fuction of the solution. Also, some emissions are not in g but in mols so the molecular weight has to be accounted for. The emissions are added directly to the `chem` tracer field on the atmospheric grid and to per species accumulators, which are printed by setting `printsums=1` . The emissions are never accumulated separately because that would require  `num_chem` 2D grids and I did not want to deal with the complication at the time. In addition, accumulating the emissions on the fire grid, which would be a natural thing to do, would require too much memory (at least at the time I wrote that part of the code 9 years ago; today the decision might be different). So the `printsums` switch causes the total accumulated values to be printed in the rsl files for the whole grid and each emission species.
