### ISSUE TITLE
Hand update on code of standalone model.

### ISSUE THREAD

**Issue by jinjiaodawang** [openwfm/WRF-SFIRE#55]
**Describe the bug**
Hand update on code of standalone model.

**To Reproduce**
Build standalone fire.exe will get error msg as below:
```
module_fr_sfire_driver.f90:1689:26:

 1689 |     fp%tempf => grid%tempf     ! temperature
      |                          1
Error: ‘tempf’ at (1) is not a member of the ‘domain’ structure
module_fr_sfire_driver.f90:1690:24:

 1690 |     fp%rhof => grid%rhof     ! surface air density
      |                        1
Error: ‘rhof’ at (1) is not a member of the ‘domain’ structure; did you mean ‘ros’?
module_fr_sfire_driver.f90:1691:30:

 1691 |     fp%ffwidth => grid%ffwidth     ! fire front width
      |                              1
Error: ‘ffwidth’ at (1) is not a member of the ‘domain’ structure
module_fr_sfire_driver.f90:1795:39:

 1795 |         call check_size(size(grid%tempf),'tempf')
      |                                       1
Error: ‘tempf’ at (1) is not a member of the ‘domain’ structure
module_fr_sfire_driver.f90:1796:38:

 1796 |         call check_size(size(grid%rhof),'rhof')
      |                                      1
Error: ‘rhof’ at (1) is not a member of the ‘domain’ structure; did you mean ‘ros’?
module_fr_sfire_driver.f90:1797:41:

 1797 |         call check_size(size(grid%ffwidth),'ffwidth')
      |                                         1
Error: ‘ffwidth’ at (1) is not a member of the ‘domain’ structure
```

I added variables to 'domain' structure. Add 3 lines into module_domain.F line 70:
```
      real, pointer, dimension(:,:)::tempf => null()
      real, pointer, dimension(:,:)::rhof => null()
      real, pointer, dimension(:,:)::ffwidth => null()
```
I am not quite sure if it is correct since I have 0 knowledge about Fortran. I set up this simulator for simulation optimization research. I set up wrf before and run an experiment on real data of the western US, now I try to run wrf-sfire to optimize the design of firefighting facilities.  I have 2 questions also:
1. If the standalone version is under development, should I run wrf from test/em_real?
2. Is there any simulation on firefighting included in wrf-sfire?

**Comment by janmandel** [comment]
@jinjiaodawang 
Thank you.  I added the variables tempf rhof ffwidth when adding Balbi ROS model #45 but the standalone is out of date. I'll make the change you suggest. 
We simulate firefighting in  WRF-SFIRE by modifying the fuel map (variable nfuel_cat) in a restart file to no fuel where fire breaks were created and then restart the simulation. Since standalone is cheap you could just rerun from the start. We have tools to read and write WRF netcdf files in matlab conveniently in https://github.com/openwfm/wrf-fire-matlab/tree/master/netcdf (I see now the readme file there is out of date).  Simulating a backfire would require a second ignition in full WRF-SFIRE not standalone because the effect of fire on the atmosphere in a backfire is important. And of course a scientific validation study. Adding a second ignition in restart could be done by modifying tign_g externally.

**Comment by jinjiaodawang** [comment]
Got it. Now I try to restart the standalone version.
Thank you for your immediate response. Closing this issue.
