### ISSUE TITLE
How to add anthro emiss PM as a tracer in wrfchem? 

### ISSUE THREAD

**Issue by liy25** [openwfm/WRF-SFIRE#65]
**Describe the bug**
i want to analysis the primary pm from anthro emiss, but when i just input PM emission for wrf to run wrf.exe, there are not PM emission variation. so i think i should use tracer module, i find some information about tracer, it is about CO and other tracer species not PM, what should i do?

**Comment by adamk0** [comment]
Custom tracers can be specified in namelist.fire_emissions when tracer_opt =2 is selected.
There are 8 tracers tr17_1 …tr17_8 that can be assigned to PM2.5, CO, NOx, etc., but these tracers will be only associated with the fire emissions.

Otherwise one can use WRF-CHEM and full chemical speciation compatible with supported chemical options (RADM2, MOZART or GOCART).

Adam Kochanski

Assistant Professor
Department of Meteorology and Climate Science
Wildfire Interdisciplinary Research Center
San Jose State University



From: liy25 ***@***.***>
Reply-To: openwfm/WRF-SFIRE ***@***.***>
Date: Wednesday, April 19, 2023 at 1:48 AM
To: openwfm/WRF-SFIRE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openwfm/WRF-SFIRE] how to add anthro emiss PM as a tracer in wrfchem? (Issue #65)


Describe the bug
i want to analysis the primary pm from anthro emiss, but when i just input PM emission for wrf to run wrf.exe, there are not PM emission variation. so i think i should use tracer module, i find some information about tracer, it is about CO and other tracer species not PM, what should i do?

**Comment by liy25** [comment]
hi Adam, i'm realy thankful to you! 
 i confused aboudt you saied "full chemical speciation compatible with supported chemical options".  i find  in the user guide that say "A tracer transport option in which the chemical mechanism, deposition, etc. has been turned off. The user must provide the emissions data for their own domain in the proper WRF data file format for this option. May be run parallel with chemistry." Seems if i want to run tracer, must turnoff the chemical mechanism?

**Comment by adamk0** [comment]
I’m not sure what this information refers to. Are you talking about tracer_opt option w/o chemistry that is for WRF-SFIRE w/o chem or for WRF-SFIRE with chem?

There are multiple ways to run the tracer.
For WRF-SFIRE w/o chem you would use tracer_opt=2, and then you would use tr17_X fields as tracers. In namelist_fiere.emission you would specify emission factors for each tracer tr17_1 tr17_2 …

For WRF-SFIRE with CHEM or WRF-CHEM you could use chem_opt =0 and non-zero tracer_opt, or chem_opt=14.
In each case you would need to create your own namelist_fiere.emission file with the list of emission factors compatible with the chemical scheme you plan to use.

We don’t use WRF-SFIRE-CHEM with tracers, and this option is not officially supported, so it will be up to you to create the appropriate namelist_fiere.emission and make sure it works.

Good luck,

Adam Kochanski

Assistant Professor
Department of Meteorology and Climate Science
Wildfire Interdisciplinary Research Center
San Jose State University



From: zeroooooooo ***@***.***>
Reply-To: openwfm/WRF-SFIRE ***@***.***>
Date: Friday, April 21, 2023 at 12:16 AM
To: openwfm/WRF-SFIRE ***@***.***>
Cc: Adam Kochanski ***@***.***>, Comment ***@***.***>
Subject: Re: [openwfm/WRF-SFIRE] how to add anthro emiss PM as a tracer in wrfchem? (Issue #65)


hi Adam, i'm realy thankful to you!
i confused aboudt you saied "full chemical speciation compatible with supported chemical options". i find in the user guide that say "A tracer transport option in which the chemical mechanism, deposition, etc. has been turned off. The user must provide the emissions data for their own domain in the proper WRF data file format for this option. May be run parallel with chemistry." Seems if i want to run tracer, must turnoff the chemical mechanism?
