### ISSUE TITLE
Killed error when running the real.exe of the wrf-sfire coupling with WRF-Chem

### ISSUE THREAD

**Issue by llsalazar** [openwfm/WRF-SFIRE#68]
I am trying to run the WRF-SFIRE coupling with chem, but when I run real.exe, the model stops and displays the message Killed on the console. I think this is because the memory is not enough, but our computer has 32 GB of memory.

These are the properties of our computer:
Memory PC Intel i9 13900K 24x 5.8 GHz, 32 GB DDR4 RAM 3000 MHz, 480 GB SSD+2000 GB HDD, NVIDIA GF RTX 3090 24GB, Windows 11 Pro[ https://amzn.eu/d/9esrgD7](https://amzn.eu/d/9esrgD7)

This is the namelist.input that we want to run:
https://drive.google.com/drive/folders/1H0QioFRBYPKEWyNCLtLWvXv6eLeYm9g9

Is 32GB of memory not enough for run wrf-sfire coupling with chem or is this error caused by something else ?

Thanks for any help

**Comment by adamk0** [comment]
I would suggest starting from running a simple small, one-domain case w/o chem, and then running a case with chem. The NCAR tutorial available at https://www2.mmm.ucar.edu/wrf/OnLineTutorial/ would be a good starting point. The real.exe program is rather independent from SFIRE, so I would suggest contacting NCAR WRF helpdesk for real.exe related issues.

Adam Kochanski

Assistant Professor
Department of Meteorology and Climate Science
Wildfire Interdisciplinary Research Center
San Jose State University



From: llsalazar ***@***.***>
Reply-To: openwfm/WRF-SFIRE ***@***.***>
Date: Wednesday, May 10, 2023 at 1:11 AM
To: openwfm/WRF-SFIRE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openwfm/WRF-SFIRE] Killed error when running the real.exe of the wrf-sfire coupling with WRF-Chem (Issue #68)


I am trying to run the WRF-SFIRE coupling with chem, but when I run real.exe, the model stops and displays the message Killed on the console. I think this is because the memory is not enough, but our computer has 32 GB of memory.

These are the properties of our computer:
Memory PC Intel i9 13900K 24x 5.8 GHz, 32 GB DDR4 RAM 3000 MHz, 480 GB SSD+2000 GB HDD, NVIDIA GF RTX 3090 24GB, Windows 11 Pro https://amzn.eu/d/9esrgD7<https://www.google.com/url?q=https://amzn.eu/d/9esrgD7&source=gmail-imap&ust=1684311065000000&usg=AOvVaw0Jq5b1CKVflh-ruz8Lh0oR>

This is the namelist.input that we want to run:
https://drive.google.com/drive/folders/1H0QioFRBYPKEWyNCLtLWvXv6eLeYm9g9<https://www.google.com/url?q=https://drive.google.com/drive/folders/1H0QioFRBYPKEWyNCLtLWvXv6eLeYm9g9&source=gmail-imap&ust=1684311065000000&usg=AOvVaw05cantjg1K7qkbPOCR4HIL>

Is 32GB of memory not enough for run wrf-sfire coupling with chem or is this error caused by something else ?

Thanks for any help
