### ISSUE TITLE
WRF_SFIRE Error

### ISSUE THREAD

**Issue by llsalazar** [openwfm/WRF-SFIRE#85]
Good morning

We want to run WRF_SFIRE for 4 domains with 9, 3, 1 km and 200 m and we want to use LES for the last domain, we had to use ndown.exe for the fourth domain, but during the execution of domain four a line starts looping at rsl.error.0000 and never stops. 

Please can someone help me? Thanks

I attach the namelist.input and the rsl.error.0000
[SFIRE.tar.gz](https://github.com/openwfm/WRF-SFIRE/files/14494536/SFIRE.tar.gz)

**Comment by adamk0** [comment]
I would suggest starting from looking into the Errors in the rsl.out.0000:

  *   Ignoring problems reading my_file_d04.txt

Continuing.  To make this a fatal error, set ignore_iofields_warn to false in namelist

  *   open_aux_u : error opening auxinput5_d01_2019-06-28_03:00:00 for reading.   100

To identify the source of the problem running the same simulation with no fire code (ifire=0) or with fire code activated but no ignition should help diagnose the problem.
The typical way to set up such simulation would be to complete it first without chemistry and verify if it runs properly, then repeat the simulation with the chemistry activated, then add the fire component.

Adam Kochanski

Associate Professor
SJSU Wildfire Interdisciplinary Research Center




From: llsalazar ***@***.***>
Date: Tuesday, March 5, 2024 at 3:30 AM
To: openwfm/WRF-SFIRE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openwfm/WRF-SFIRE] WRF_SFIRE Error (Issue #85)

Good morning

We want to run WRF_SFIRE for 4 domains with 9, 3, 1 km and 200 m and we want to use LES for the last domain, we had to use ndown.exe for the fourth domain, but during the execution of domain four a line starts looping at rsl.error.0000 and never stops.

Please can someone help me? Thanks

I attach the namelist.input and the rsl.error.0000
SFIRE.tar.gz<https://www.google.com/url?q=https://github.com/openwfm/WRF-SFIRE/files/14494536/SFIRE.tar.gz&source=gmail-imap&ust=1710243032000000&usg=AOvVaw3_SyBu6svHt7Z7RtdWuJty>

**Comment by janmandel** [comment]
@llsalazar 
Can you please provide some details with "line starts looping at rsl.error.0000 and never stops". I see in your rsl.error.0000 multiple lines with a warning about extinction moisture, is that the looping you are referring to? Also, I see at the beginnng 
git commit c959580092191b315d936566361314f9cab669ec 1 file changed, 1 insertion(+), 1 deletion(-)
which means something changed against the version on github and we do not know what.  If you could run git diff in the directory with the code and send the output please. Thanks!

**Comment by llsalazar** [comment]
Good morning @adamk0 @janmandel 

The problem with the sfire was solved, this problem appeared because the way it managed the nodes was not correct. We managed to run a successful simulation with WRF-SFIRE

Thank you for your help

**Comment by adamk0** [comment]
Thanks for the update.
Could you share more detail on how you solved the issue?

Adam Kochanski

Associate Professor
SJSU Wildfire Interdisciplinary Research Center




From: llsalazar ***@***.***>
Date: Friday, March 15, 2024 at 4:15 AM
To: openwfm/WRF-SFIRE ***@***.***>
Cc: Adam Kochanski ***@***.***>, Mention ***@***.***>
Subject: Re: [openwfm/WRF-SFIRE] WRF_SFIRE Error (Issue #85)

Good morning @adamk0<https://www.google.com/url?q=https://github.com/adamk0&source=gmail-imap&ust=1711106133000000&usg=AOvVaw2HdraAB85ZdEbYZ-t30WIa> @janmandel<https://www.google.com/url?q=https://github.com/janmandel&source=gmail-imap&ust=1711106133000000&usg=AOvVaw2sT93ptvkwmaZ7n8yC1uLP>

The problem with the sfire was solved, this problem appeared because the way it managed the nodes was not correct. We managed to run a successful simulation with WRF-SFIRE

Thank you for your help
